# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Unit Test and Build CLI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     # checkout the repo
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install Coverlet
        run: cd CLIUnitTests && dotnet add package coverlet.msbuild
      - name: Navigate to CLI
        run: cd CLI && ls
      - name: Test
        run: dotnet test CLI /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=test-results.trx" 
      - name: Build
        run: dotnet build CLI
      - name: Dir
        run: cd CLIUnitTests
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Dotnet Tests            # Name of the check run which will be created
          path: unitTests/TestResults/test-results.trx   # Path to test results
          reporter: dotnet-trx        # Format of test results
      - name: CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./unitTests/coverage.opencover.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
