name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     # checkout the repo
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Dir
        run: cd UML && pwd
      - name: Build
        run: dotnet build UML
      - name: Test
        run: dotnet test unitTests --logger "trx;LogFileName=test-results.trx"
      - name: Dir
        run: cd unitTests && cd TestReults && pwd && ls
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Dotnet Tests            # Name of the check run which will be created
          path: unitTests/TestResults/test-results   # Path to test results
          reporter: dotnet-trx        # Format of test results

